### ISSUE TITLE
Msbuild issue in 6.0.2 preview

### ISSUE THREAD

**Issue by andriy-tsvikla** [byme8/ZeroQL#75]
**Describe the bug**
When running build using visual studio it causes error
```
Error	MSB4018	The "ZeroQLBuildTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at ZeroQL.Core.Config.ZeroQLSchema.GetJsonSchema()
   at ZeroQL.Core.Config.ZeroQLConfigReader.ReadConfig(String configFile)
   at ZeroQL.Tasks.ZeroQLBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**How to Reproduce**
Build with visual studio

**Expected behavior**
Build should complete without error

**Screenshots**

**Environment (please complete the following information):**
 - Nuget package version [6.0.0]
 - IDE: [VS, VS for Mac, Rider, VS Code]
 - .Net Version [6.0.400, 7.0.100]

**Additional context**
It seems that issue is in **.nuget\packages\zeroql\6.1.0-preview.2\build\net6.0\ZeroQL.props** file when replaced with **.nuget\packages\zeroql\6.0.0\build\net6.0\ZeroQL.props** - build works

**Comment by byme8** [comment]
I managed to reproduce in Visual Studio. However, it works fine in Rider and via CLI. Will have a look at it.

**Comment by byme8** [comment]
Checkout v6.1.0-preview.4. The issue with msbuild in VS should be fixed.
